import Link from "next/link"
import "./globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div>
          <Link href="/about"> About |</Link>
          <Link href="/new"> New |</Link>
          <Link href="/edit/1"> Edit</Link>
        </div>
        {children}
      </body>
    </html>
  )
}
