import Link from "next/link";
import "./globals.css";
import { TaskProvider } from "@/context/TaskContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div>
          <Link href="/new"> New |</Link>
          <Link href="/edit/1"> Edit</Link>
        </div>
        <TaskProvider>{children}</TaskProvider>
      </body>
    </html>
  );
}
